sonar.organization=mirasen-io
sonar.projectKey=mirasen-io_license-gate
sonar.projectName=license-gate

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage*/**/lcov.info

# sonar.exclusions=src/routes/**/*
sonar.cpd.exclusions=tests/**/*
